// lib/ui/widgets/eas_codes.dart

/// A map of all official EAS Event Codes and their descriptions.
const Map<String, String> easEventCodes = {
  'ADR': 'Administrative Message',
  'AVA': 'Avalanche Watch',
  'AVW': 'Avalanche Warning',
  'BZW': 'Blizzard Warning',
  'CAE': 'Child Abduction Emergency',
  'CDW': 'Civil Danger Warning',
  'CEM': 'Civil Emergency Message',
  'CFA': 'Coastal Flood Watch',
  'CFW': 'Coastal Flood Warning',
  'DMO': 'Practice/Demo Warning',
  'DSW': 'Dust Storm Warning',
  'EAN': 'Emergency Action Notification',
  'EAT': 'Emergency Action Termination',
  'EQW': 'Earthquake Warning',
  'EVI': 'Evacuation Immediate',
  'EWW': 'Extreme Wind Warning',
  'FCW': 'Flash Flood Warning',
  'FFA': 'Flash Flood Watch',
  'FFS': 'Flash Flood Statement',
  'FLA': 'Flood Watch',
  'FLW': 'Flood Warning',
  'FLS': 'Flood Statement',
  'FRW': 'Fire Warning',
  'FSW': 'Flash Freeze Warning',
  'FZW': 'Freeze Warning',
  'HLS': 'Hurricane Local Statement',
  'HMW': 'Hazardous Materials Warning',
  'HUA': 'Hurricane Watch',
  'HUW': 'Hurricane Warning',
  'HWA': 'High Wind Watch',
  'HWW': 'High Wind Warning',
  'LAE': 'Local Area Emergency',
  'LEW': 'Law Enforcement Warning',
  'NAT': 'National Audible Test',
  'NIC': 'National Information Center',
  'NMN': 'Network Message Notification',
  'NPT': 'National Periodic Test',
  'NUW': 'Nuclear Power Plant Warning',
  'RHW': 'Radiological Hazard Warning',
  'RMT': 'Required Monthly Test',
  'RWT': 'Required Weekly Test',
  'SMW': 'Special Marine Warning',
  'SPS': 'Special Weather Statement',
  'SPW': 'Shelter in Place Warning',
  'SQW': 'Snow Squall Warning',
  'SSA': 'Storm Surge Watch',
  'SSW': 'Storm Surge Warning',
  'SVA': 'Severe Thunderstorm Watch',
  'SVR': 'Severe Thunderstorm Warning',
  'SVS': 'Severe Weather Statement',
  'TOA': 'Tornado Watch',
  'TOR': 'Tornado Warning',
  'TRA': 'Tropical Storm Watch',
  'TRW': 'Tropical Storm Warning',
  'TSA': 'Tsunami Watch',
  'TSW': 'Tsunami Warning',
  'VOW': 'Volcano Warning',
  'WSA': 'Winter Storm Watch',
  'WSW': 'Winter Storm Warning',
  'WFA': 'Wildfire Watch',
  'WFW': 'Wildfire Warning',
  // Unrecognized / Practice Codes
  'BWW': 'Boil Water Warning',
  'BLU': 'Blue Alert',
  'CHW': 'Chemical Hazard Warning',
  'DBW': 'Dam Break Warning',
  'DEW': 'Debris Warning',
  'IBW': 'Iceberg Warning',
  'IFW': 'Industrial Fire Warning',
  'LSW': 'Landslide Warning',
  'NWS': 'National Weather Service',
  'SMF': 'Smoke Warning',
  'WCN': 'Weather Information',
};